// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package overmind is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	NewMessageReq
	NewMessageAck
	ClubReq
	ClubAck
	ChatNewMessageReq
	ChatNewMessageAck
	ChatMarkReadReq
	ChatMarkReadAck
	LiveComment
	LiveAnonymousComment
	SystemNotice
	LiveNewIteractionReq
	LiveNewIteractionAck
	BroadcastReq
	BroadcastAck
*/
package overmind

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// type = 1
type NewMessageReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewMessageReq) Reset()                    { *m = NewMessageReq{} }
func (m *NewMessageReq) String() string            { return proto.CompactTextString(m) }
func (*NewMessageReq) ProtoMessage()               {}
func (*NewMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NewMessageAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewMessageAck) Reset()                    { *m = NewMessageAck{} }
func (m *NewMessageAck) String() string            { return proto.CompactTextString(m) }
func (*NewMessageAck) ProtoMessage()               {}
func (*NewMessageAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// type = 6
type ClubReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClubReq) Reset()                    { *m = ClubReq{} }
func (m *ClubReq) String() string            { return proto.CompactTextString(m) }
func (*ClubReq) ProtoMessage()               {}
func (*ClubReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ClubAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClubAck) Reset()                    { *m = ClubAck{} }
func (m *ClubAck) String() string            { return proto.CompactTextString(m) }
func (*ClubAck) ProtoMessage()               {}
func (*ClubAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// type = 7
type ChatNewMessageReq struct {
	Mid              *uint32 `protobuf:"varint,1,req,name=mid" json:"mid,omitempty"`
	Cid              *uint32 `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	MidExtend        *uint64 `protobuf:"varint,3,opt,name=mid_extend" json:"mid_extend,omitempty"`
	CidExtend        *uint64 `protobuf:"varint,4,opt,name=cid_extend" json:"cid_extend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatNewMessageReq) Reset()                    { *m = ChatNewMessageReq{} }
func (m *ChatNewMessageReq) String() string            { return proto.CompactTextString(m) }
func (*ChatNewMessageReq) ProtoMessage()               {}
func (*ChatNewMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChatNewMessageReq) GetMid() uint32 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

func (m *ChatNewMessageReq) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *ChatNewMessageReq) GetMidExtend() uint64 {
	if m != nil && m.MidExtend != nil {
		return *m.MidExtend
	}
	return 0
}

func (m *ChatNewMessageReq) GetCidExtend() uint64 {
	if m != nil && m.CidExtend != nil {
		return *m.CidExtend
	}
	return 0
}

type ChatNewMessageAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChatNewMessageAck) Reset()                    { *m = ChatNewMessageAck{} }
func (m *ChatNewMessageAck) String() string            { return proto.CompactTextString(m) }
func (*ChatNewMessageAck) ProtoMessage()               {}
func (*ChatNewMessageAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// type = 8
type ChatMarkReadReq struct {
	Mid              *uint32 `protobuf:"varint,1,req,name=mid" json:"mid,omitempty"`
	Cid              *uint32 `protobuf:"varint,2,req,name=cid" json:"cid,omitempty"`
	MidExtend        *uint64 `protobuf:"varint,3,opt,name=mid_extend" json:"mid_extend,omitempty"`
	CidExtend        *uint64 `protobuf:"varint,4,opt,name=cid_extend" json:"cid_extend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMarkReadReq) Reset()                    { *m = ChatMarkReadReq{} }
func (m *ChatMarkReadReq) String() string            { return proto.CompactTextString(m) }
func (*ChatMarkReadReq) ProtoMessage()               {}
func (*ChatMarkReadReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChatMarkReadReq) GetMid() uint32 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

func (m *ChatMarkReadReq) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *ChatMarkReadReq) GetMidExtend() uint64 {
	if m != nil && m.MidExtend != nil {
		return *m.MidExtend
	}
	return 0
}

func (m *ChatMarkReadReq) GetCidExtend() uint64 {
	if m != nil && m.CidExtend != nil {
		return *m.CidExtend
	}
	return 0
}

type ChatMarkReadAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChatMarkReadAck) Reset()                    { *m = ChatMarkReadAck{} }
func (m *ChatMarkReadAck) String() string            { return proto.CompactTextString(m) }
func (*ChatMarkReadAck) ProtoMessage()               {}
func (*ChatMarkReadAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// type = 9
type LiveComment struct {
	Cid                    *uint64 `protobuf:"varint,1,req,name=cid" json:"cid,omitempty"`
	Uid                    *uint64 `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	Time                   *uint32 `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	UserName               *string `protobuf:"bytes,4,req,name=user_name" json:"user_name,omitempty"`
	UserAvatar             *string `protobuf:"bytes,5,req,name=user_avatar" json:"user_avatar,omitempty"`
	Content                *string `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	IsVerified             *bool   `protobuf:"varint,7,opt,name=is_verified" json:"is_verified,omitempty"`
	ReplyUid               *uint64 `protobuf:"varint,8,opt,name=reply_uid" json:"reply_uid,omitempty"`
	ReplyUserName          *string `protobuf:"bytes,9,opt,name=reply_user_name" json:"reply_user_name,omitempty"`
	FriendWithAnchorperson *bool   `protobuf:"varint,10,opt,name=friend_with_anchorperson" json:"friend_with_anchorperson,omitempty"`
	XXX_unrecognized       []byte  `json:"-"`
}

func (m *LiveComment) Reset()                    { *m = LiveComment{} }
func (m *LiveComment) String() string            { return proto.CompactTextString(m) }
func (*LiveComment) ProtoMessage()               {}
func (*LiveComment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LiveComment) GetCid() uint64 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *LiveComment) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LiveComment) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *LiveComment) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *LiveComment) GetUserAvatar() string {
	if m != nil && m.UserAvatar != nil {
		return *m.UserAvatar
	}
	return ""
}

func (m *LiveComment) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *LiveComment) GetIsVerified() bool {
	if m != nil && m.IsVerified != nil {
		return *m.IsVerified
	}
	return false
}

func (m *LiveComment) GetReplyUid() uint64 {
	if m != nil && m.ReplyUid != nil {
		return *m.ReplyUid
	}
	return 0
}

func (m *LiveComment) GetReplyUserName() string {
	if m != nil && m.ReplyUserName != nil {
		return *m.ReplyUserName
	}
	return ""
}

func (m *LiveComment) GetFriendWithAnchorperson() bool {
	if m != nil && m.FriendWithAnchorperson != nil {
		return *m.FriendWithAnchorperson
	}
	return false
}

type LiveAnonymousComment struct {
	Cid              *uint64 `protobuf:"varint,1,req,name=cid" json:"cid,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	Time             *uint32 `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	UserName         *string `protobuf:"bytes,4,req,name=user_name" json:"user_name,omitempty"`
	UserAvatar       *string `protobuf:"bytes,5,req,name=user_avatar" json:"user_avatar,omitempty"`
	Content          *string `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LiveAnonymousComment) Reset()                    { *m = LiveAnonymousComment{} }
func (m *LiveAnonymousComment) String() string            { return proto.CompactTextString(m) }
func (*LiveAnonymousComment) ProtoMessage()               {}
func (*LiveAnonymousComment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LiveAnonymousComment) GetCid() uint64 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *LiveAnonymousComment) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *LiveAnonymousComment) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *LiveAnonymousComment) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *LiveAnonymousComment) GetUserAvatar() string {
	if m != nil && m.UserAvatar != nil {
		return *m.UserAvatar
	}
	return ""
}

func (m *LiveAnonymousComment) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type SystemNotice struct {
	Cid              *uint64 `protobuf:"varint,1,req,name=cid" json:"cid,omitempty"`
	Time             *uint32 `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	Type             *string `protobuf:"bytes,3,req,name=type" json:"type,omitempty"`
	Content          *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	Style            *string `protobuf:"bytes,5,opt,name=style" json:"style,omitempty"`
	Uid              *uint64 `protobuf:"varint,6,opt,name=uid" json:"uid,omitempty"`
	UserName         *string `protobuf:"bytes,7,opt,name=user_name" json:"user_name,omitempty"`
	UserAvatar       *string `protobuf:"bytes,8,opt,name=user_avatar" json:"user_avatar,omitempty"`
	IsVerified       *bool   `protobuf:"varint,9,opt,name=is_verified" json:"is_verified,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SystemNotice) Reset()                    { *m = SystemNotice{} }
func (m *SystemNotice) String() string            { return proto.CompactTextString(m) }
func (*SystemNotice) ProtoMessage()               {}
func (*SystemNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SystemNotice) GetCid() uint64 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *SystemNotice) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *SystemNotice) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *SystemNotice) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *SystemNotice) GetStyle() string {
	if m != nil && m.Style != nil {
		return *m.Style
	}
	return ""
}

func (m *SystemNotice) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SystemNotice) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *SystemNotice) GetUserAvatar() string {
	if m != nil && m.UserAvatar != nil {
		return *m.UserAvatar
	}
	return ""
}

func (m *SystemNotice) GetIsVerified() bool {
	if m != nil && m.IsVerified != nil {
		return *m.IsVerified
	}
	return false
}

type LiveNewIteractionReq struct {
	Nid               *uint64                 `protobuf:"varint,1,req,name=nid" json:"nid,omitempty"`
	Lid               *uint64                 `protobuf:"varint,2,req,name=lid" json:"lid,omitempty"`
	AudienceNum       *uint32                 `protobuf:"varint,3,opt,name=audience_num" json:"audience_num,omitempty"`
	LikeNum           *uint32                 `protobuf:"varint,4,opt,name=like_num" json:"like_num,omitempty"`
	Comments          []*LiveComment          `protobuf:"bytes,5,rep,name=comments" json:"comments,omitempty"`
	AudienceAccumNum  *uint32                 `protobuf:"varint,6,opt,name=audience_accum_num" json:"audience_accum_num,omitempty"`
	AnonymousComments []*LiveAnonymousComment `protobuf:"bytes,7,rep,name=anonymous_comments" json:"anonymous_comments,omitempty"`
	SystemNotice      *SystemNotice           `protobuf:"bytes,8,opt,name=system_notice" json:"system_notice,omitempty"`
	XXX_unrecognized  []byte                  `json:"-"`
}

func (m *LiveNewIteractionReq) Reset()                    { *m = LiveNewIteractionReq{} }
func (m *LiveNewIteractionReq) String() string            { return proto.CompactTextString(m) }
func (*LiveNewIteractionReq) ProtoMessage()               {}
func (*LiveNewIteractionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LiveNewIteractionReq) GetNid() uint64 {
	if m != nil && m.Nid != nil {
		return *m.Nid
	}
	return 0
}

func (m *LiveNewIteractionReq) GetLid() uint64 {
	if m != nil && m.Lid != nil {
		return *m.Lid
	}
	return 0
}

func (m *LiveNewIteractionReq) GetAudienceNum() uint32 {
	if m != nil && m.AudienceNum != nil {
		return *m.AudienceNum
	}
	return 0
}

func (m *LiveNewIteractionReq) GetLikeNum() uint32 {
	if m != nil && m.LikeNum != nil {
		return *m.LikeNum
	}
	return 0
}

func (m *LiveNewIteractionReq) GetComments() []*LiveComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *LiveNewIteractionReq) GetAudienceAccumNum() uint32 {
	if m != nil && m.AudienceAccumNum != nil {
		return *m.AudienceAccumNum
	}
	return 0
}

func (m *LiveNewIteractionReq) GetAnonymousComments() []*LiveAnonymousComment {
	if m != nil {
		return m.AnonymousComments
	}
	return nil
}

func (m *LiveNewIteractionReq) GetSystemNotice() *SystemNotice {
	if m != nil {
		return m.SystemNotice
	}
	return nil
}

type LiveNewIteractionAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LiveNewIteractionAck) Reset()                    { *m = LiveNewIteractionAck{} }
func (m *LiveNewIteractionAck) String() string            { return proto.CompactTextString(m) }
func (*LiveNewIteractionAck) ProtoMessage()               {}
func (*LiveNewIteractionAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// type = 253
type BroadcastReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BroadcastReq) Reset()                    { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string            { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()               {}
func (*BroadcastReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type BroadcastAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BroadcastAck) Reset()                    { *m = BroadcastAck{} }
func (m *BroadcastAck) String() string            { return proto.CompactTextString(m) }
func (*BroadcastAck) ProtoMessage()               {}
func (*BroadcastAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func init() {
	proto.RegisterType((*NewMessageReq)(nil), "overmind.NewMessageReq")
	proto.RegisterType((*NewMessageAck)(nil), "overmind.NewMessageAck")
	proto.RegisterType((*ClubReq)(nil), "overmind.ClubReq")
	proto.RegisterType((*ClubAck)(nil), "overmind.ClubAck")
	proto.RegisterType((*ChatNewMessageReq)(nil), "overmind.ChatNewMessageReq")
	proto.RegisterType((*ChatNewMessageAck)(nil), "overmind.ChatNewMessageAck")
	proto.RegisterType((*ChatMarkReadReq)(nil), "overmind.ChatMarkReadReq")
	proto.RegisterType((*ChatMarkReadAck)(nil), "overmind.ChatMarkReadAck")
	proto.RegisterType((*LiveComment)(nil), "overmind.LiveComment")
	proto.RegisterType((*LiveAnonymousComment)(nil), "overmind.LiveAnonymousComment")
	proto.RegisterType((*SystemNotice)(nil), "overmind.SystemNotice")
	proto.RegisterType((*LiveNewIteractionReq)(nil), "overmind.LiveNewIteractionReq")
	proto.RegisterType((*LiveNewIteractionAck)(nil), "overmind.LiveNewIteractionAck")
	proto.RegisterType((*BroadcastReq)(nil), "overmind.BroadcastReq")
	proto.RegisterType((*BroadcastAck)(nil), "overmind.BroadcastAck")
}

var fileDescriptor0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x72, 0xd3, 0x30,
	0x10, 0x9d, 0x24, 0x6e, 0x62, 0x6f, 0x62, 0x42, 0xdc, 0x52, 0x3c, 0x1c, 0x98, 0x8c, 0x2f, 0xe4,
	0x42, 0x0e, 0x3d, 0x72, 0x2b, 0x39, 0x31, 0x43, 0x7b, 0x68, 0x87, 0xb3, 0x47, 0xc8, 0x5b, 0xa2,
	0x49, 0x24, 0x05, 0x49, 0x4e, 0xc8, 0x1f, 0xf0, 0x1b, 0x7c, 0x12, 0x7f, 0x84, 0x24, 0xdb, 0xa9,
	0x0d, 0x9d, 0xe1, 0xd2, 0x5b, 0xf6, 0x6d, 0xfc, 0xde, 0xdb, 0xb7, 0x6b, 0x43, 0xcc, 0x51, 0x6b,
	0xf2, 0x0d, 0x97, 0x3b, 0x25, 0x8d, 0x4c, 0x42, 0xb9, 0x47, 0xc5, 0x99, 0x28, 0xb2, 0x29, 0xc4,
	0xb7, 0x78, 0xb8, 0xa9, 0xba, 0x77, 0xf8, 0xbd, 0x0b, 0x5c, 0xd3, 0x4d, 0x16, 0xc1, 0x68, 0xb5,
	0x2d, 0xbf, 0xba, 0x5e, 0xfd, 0xd3, 0xa1, 0x5f, 0x60, 0xb6, 0x5a, 0x13, 0xd3, 0x79, 0x36, 0x19,
	0xc3, 0x80, 0xb3, 0x22, 0xed, 0xcd, 0xfb, 0x8b, 0xd8, 0x15, 0xd4, 0x16, 0x7d, 0x5f, 0x24, 0x00,
	0xb6, 0x93, 0xe3, 0x0f, 0x83, 0xa2, 0x48, 0x07, 0xf3, 0xde, 0x22, 0x70, 0x18, 0x7d, 0xc4, 0x02,
	0x87, 0x65, 0xe7, 0x7f, 0xd3, 0x3a, 0xad, 0x7b, 0x98, 0x3a, 0xf0, 0x86, 0xa8, 0xcd, 0x1d, 0x92,
	0xe2, 0x79, 0x94, 0x66, 0x5d, 0x52, 0xa7, 0xf3, 0xbb, 0x07, 0xe3, 0xcf, 0x6c, 0x8f, 0x2b, 0xc9,
	0x39, 0x0a, 0xd3, 0xf0, 0x3a, 0x91, 0xc0, 0x15, 0x65, 0x2d, 0x12, 0x24, 0x13, 0x08, 0x0c, 0xe3,
	0x68, 0xe9, 0x9d, 0xe4, 0x0c, 0xa2, 0x52, 0xa3, 0xca, 0x05, 0xb1, 0x50, 0x60, 0xa1, 0x28, 0x39,
	0x87, 0xb1, 0x87, 0xc8, 0x9e, 0x18, 0xa2, 0xd2, 0x33, 0x0f, 0x4e, 0x61, 0x44, 0xa5, 0xb0, 0x1e,
	0x4c, 0x3a, 0xb4, 0x1e, 0xfc, 0xbf, 0x98, 0xce, 0xed, 0x2a, 0xd8, 0x03, 0xc3, 0x22, 0x1d, 0x59,
	0x30, 0x74, 0x6c, 0x0a, 0x77, 0xdb, 0x63, 0xee, 0xe4, 0x42, 0xef, 0xff, 0x35, 0x4c, 0x6b, 0xe8,
	0x24, 0x13, 0x79, 0x82, 0x39, 0xa4, 0x0f, 0x8a, 0xd9, 0xa1, 0xf2, 0x03, 0x33, 0xeb, 0x9c, 0x08,
	0xba, 0x96, 0x6a, 0x87, 0x4a, 0x4b, 0x91, 0x82, 0x63, 0xcb, 0x0e, 0x70, 0xe1, 0x46, 0xba, 0x16,
	0x52, 0x1c, 0xb9, 0x2c, 0xf5, 0xff, 0x66, 0x8b, 0x9e, 0x69, 0xb6, 0xec, 0x57, 0x0f, 0x26, 0xf7,
	0x47, 0x6d, 0x90, 0xdf, 0x4a, 0xc3, 0x28, 0x76, 0x15, 0x1b, 0x91, 0x6a, 0x67, 0xae, 0x3a, 0xee,
	0x2a, 0xc9, 0x0e, 0x55, 0x25, 0x18, 0xc3, 0x99, 0x36, 0xc7, 0x2d, 0x5a, 0x29, 0x37, 0x74, 0xed,
	0x76, 0xe8, 0xa3, 0xe9, 0xf8, 0x1b, 0x35, 0xa9, 0xb6, 0xfd, 0x85, 0x4f, 0x45, 0x1d, 0xf9, 0x70,
	0x7e, 0xf6, 0xab, 0x74, 0xec, 0xb9, 0x7d, 0x32, 0xa8, 0x08, 0x35, 0x4c, 0x8a, 0xfa, 0xbc, 0x44,
	0x3b, 0x9d, 0xed, 0x69, 0xf3, 0x17, 0x30, 0x21, 0x65, 0x61, 0x23, 0xa7, 0x98, 0x8b, 0x92, 0xfb,
	0x03, 0x8b, 0x93, 0x97, 0x10, 0x6e, 0xd9, 0xa6, 0x42, 0x02, 0x8f, 0xbc, 0x83, 0x90, 0x56, 0x51,
	0x6b, 0x6b, 0x7b, 0xb0, 0x18, 0x5f, 0xbd, 0x5a, 0x36, 0x2f, 0xdd, 0xb2, 0x7d, 0x64, 0x6f, 0x20,
	0x39, 0x11, 0x12, 0x4a, 0x4b, 0xee, 0x49, 0x86, 0x9e, 0xe4, 0x83, 0xed, 0x35, 0x8b, 0xcb, 0x4f,
	0x74, 0x23, 0x4f, 0xf7, 0xb6, 0x4b, 0xf7, 0xcf, 0x82, 0xdf, 0x43, 0xac, 0x7d, 0xfc, 0xb9, 0xf0,
	0xf9, 0xfb, 0x1c, 0xc6, 0x57, 0x97, 0x8f, 0x8f, 0xb5, 0xb7, 0x93, 0x5d, 0x3e, 0x91, 0x84, 0x7b,
	0x27, 0x5e, 0xc0, 0xe4, 0xa3, 0x92, 0xa4, 0xa0, 0x44, 0x1b, 0xf7, 0x09, 0x68, 0xd7, 0xb6, 0xff,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x88, 0x1c, 0x86, 0x59, 0x04, 0x00, 0x00,
}
